version: '3'
services:
  jobmanager:
    image: flink:1.19-java11
    container_name: jobmanager
    ports:
      - "8081:8081" # for web ui
      - "6123:6123" # rpc port
      - "6124:6124" # blob server ?
    command: jobmanager
    volumes:
      - ./jars:/jars
    environment:
      - |
        FLINK_PROPERTIES=
        web.upload.dir: /jars
        jobmanager.rpc.address: jobmanager
    networks:
      - flink-network

  taskmanager:
    image: flink:1.19-java11
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        taskmanager.memory.process.size: 6g
        taskmanager.cpu.cores: 3
    deploy:
      replicas: 1
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge