version: '3'
services:
  jobmanager:
    image: flink:1.19-java11
    container_name: jobmanager
    ports:
      - "8081:8081" # for web ui
      - "6123:6123" # rpc port
      - "6124:6124" # blob server
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        web.upload.dir: /jars
        jobmanager.rpc.address: <JOBMANAGER-MACHINE-IP>
    networks:
      - flink-network

  taskmanager:
    image: flink:1.19-java11
    depends_on:
      - jobmanager
    command: taskmanager
    ports:
      - "6125:6125"
      - "6126:6126"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: <JOBMANAGER-MACHINE-IP>
        taskmanager.host: <TASKMANAGER-MACHINE-IP>
        taskmanager.numberOfTaskSlots: 1
        taskmanager.memory.process.size: 6g
        taskmanager.data.port : 6125
        taskmanager.rpc.port : 6126
        taskmanager.cpu.cores: 3
    deploy:
      replicas: 1
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge